version: "3.9"

services:
  simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: simple

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    container_name: pyspark
  
  aws-cli:
    build:
      context: .
      dockerfile: Dockerfile.awscli
    container_name: aws-cli

networks:
  default: